pipeline {
    agent any

    tools {
        terraform 'terraform'
    }

    stages {
        stage('Terraform init') {
            environment {
            AWS_ACCESS_KEYS = credentials('aws_rootkey')
            }
            steps {
                sh 'terraform init'   
            }        
        }
    }

    stages {
        stage('directory') {
            steps {
                sh 'll'   
            }        
        }
    }
        stage('Terraform apply') {
            environment {
            AWS_ACCESS_KEYS = credentials('aws_rootkey')
            }
             steps {
                sh 'terraform apply --auto-approve'   
            }        
        }
    }
}
